# Generated by Django 4.2.1 on 2023-05-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_merchant_id_order_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
