# Generated by Django 4.2.1 on 2023-05-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
